export interface TemplateField {
  label: string;
  type: 'text' | 'dropdown';
  defaultValue: string;
  optionsKey?: keyof TemplateOptions;
}

export interface TemplateOptions {
  style?: { value: string; label:string }[];
  lighting?: { value: string; label:string }[];
  composition?: { value: string; label:string }[];
  mood?: { value: string; label:string }[];
  platform?: { value: string; label:string }[];
}

export interface SubTemplate {
  key: string;
  label: string;
  promptTemplate: string;
  fields: Record<string, TemplateField>;
  negativePrompt: string;
  aspectRatio: '16:9' | '1:1' | '9:16' | '4:3' | '3:4';
}

export interface UseCaseTemplate {
  label:string;
  subTemplates: SubTemplate[];
  options: TemplateOptions;
}

export const promptTemplates: Record<string, { label: string; useCases: Record<string, UseCaseTemplate> }> = {
  gaming: {
    label: '游戏行业',
    useCases: {
      character_concept: {
        label: '角色概念艺术',
        subTemplates: [
          // 5个角色表
          { key: 'dwarven_runesmith', label: '角色表 | 矮人符文工匠', promptTemplate: 'Character sheet of a {personality} master dwarven runesmith, {style}, featuring {defining_features}. He wears {clothing}, holding {weapon}. Game setting is {game_setting}. Color palette is {color_palette}. Visual style similar to {references}. Front, side, and back view on a neutral background.', fields: { personality: { label: '性格特征', type: 'text', defaultValue: 'grumpy and proud' }, style: { label: '风格', type: 'text', defaultValue: 'realistic 3d render style' }, defining_features: { label: '定义特征', type: 'text', defaultValue: 'a magnificent braided beard with metal rings, soot stains on his face, and complex goggles on his forehead' }, clothing: { label: '服装元素', type: 'text', defaultValue: 'a heavy leather apron over sturdy robes' }, weapon: { label: '武器/工具', type: 'text', defaultValue: 'a giant warhammer with glowing lava-like runes' }, game_setting: { label: '游戏背景', type: 'text', defaultValue: 'a subterranean mountain city' }, color_palette: { label: '调色板', type: 'text', defaultValue: 'earthy tones, brass, and fiery orange' }, references: { label: '参考作品', type: 'text', defaultValue: 'World of Warcraft and Baldur\'s Gate 3' }, }, negativePrompt: 'cartoon, anime, 2d, flat, slender, elf, clean, smooth skin, poorly drawn hands, blurry, disfigured', aspectRatio: '16:9', },
          { key: 'tribal_storm_shaman', label: '角色表 | 部落风暴萨满', promptTemplate: 'Character sheet of a {personality} female tribal storm shaman, {style}, featuring {defining_features}. She wears {clothing}, holding {weapon}. Game setting is {game_setting}. Color palette is {color_palette}. Visual style similar to {references}. Front, side, and back view on a neutral background.', fields: { personality: { label: '性格特征', type: 'text', defaultValue: 'wise and wild' }, style: { label: '风格', type: 'text', defaultValue: 'stylized realistic hand-drawn style' }, defining_features: { label: '定义特征', type: 'text', defaultValue: 'lightning-like body paint and feathers braided into her hair' }, clothing: { label: '服装元素', type: 'text', defaultValue: 'layered clothing made from beast hides and bone armor' }, weapon: { label: '武器/工具', type: 'text', defaultValue: 'a shamanic totem with a storm crystal' }, game_setting: { label: '游戏背景', type: 'text', defaultValue: 'a nomadic tribe on a primal world' }, color_palette: { label: '调色板', type: 'text', defaultValue: 'storm grey, sky blue, and lightning yellow' }, references: { label: '参考作品', type: 'text', defaultValue: 'Horizon Zero Dawn and Princess Mononoke' }, }, negativePrompt: 'modern, city, technology, metal armor, cute, anime, clean, pristine, poorly drawn face, blurry', aspectRatio: '16:9', },
          { key: 'wasteland_scavenger', label: '角色表 | 废土拾荒者', promptTemplate: 'Character sheet of a {personality} female wasteland scavenger, {style}, featuring {defining_features}. She wears {clothing}, holding {weapon}. Game setting is {game_setting}. Color palette is {color_palette}. Visual style similar to {references}. Front, side, and back view on a neutral background.', fields: { personality: { label: '性格特征', type: 'text', defaultValue: 'resourceful and wary' }, style: { label: '风格', type: 'text', defaultValue: 'realistic hand-drawn texture style' }, defining_features: { label: '定义特征', type: 'text', defaultValue: 'a long scar on her cheek and a crude prosthetic arm made of junk' }, clothing: { label: '服装元素', type: 'text', defaultValue: 'a patched-up asymmetrical duster and a large backpack full of salvaged parts' }, weapon: { label: '武器/工具', type: 'text', defaultValue: 'a modified harpoon gun' }, game_setting: { label: '游戏背景', type: 'text', defaultValue: 'a post-apocalyptic desert' }, color_palette: { label: '调色板', type: 'text', defaultValue: 'faded, dusty colors with yellow accents' }, references: { label: '参考作品', type: 'text', defaultValue: 'Fallout 4 and The Last of Us' }, }, negativePrompt: 'clean, pristine, new, futuristic, fantasy, magic, cute, anime, poorly drawn face, blurry, symmetrical', aspectRatio: '16:9', },
          { key: 'kitsune_trickster', label: '角色表 | 狐妖诡术师', promptTemplate: 'Character sheet of a {personality} male kitsune trickster, {style}, featuring {defining_features}. He wears {clothing}, holding {weapon}. Game setting is {game_setting}. Color palette is {color_palette}. Visual style similar to {references}. Front, side, and back view on a neutral background.', fields: { personality: { label: '性格特征', type: 'text', defaultValue: 'cunning and elegant' }, style: { label: '风格', type: 'text', defaultValue: 'hand-drawn anime style' }, defining_features: { label: '定义特征', type: 'text', defaultValue: 'three fluffy fox tails and red facial markings' }, clothing: { label: '服装元素', type: 'text', defaultValue: 'an ornate silk kimono with long sleeves and soul bells on his belt' }, weapon: { label: '武器/工具', type: 'text', defaultValue: 'a paper fan' }, game_setting: { label: '游戏背景', type: 'text', defaultValue: 'a fantasy world with a spirit realm' }, color_palette: { label: '调色板', type: 'text', defaultValue: 'soft pastels with indigo and gold' }, references: { label: '参考作品', type: 'text', defaultValue: 'Genshin Impact and Okami' }, }, negativePrompt: 'photorealistic, realistic, 3d render, gritty, muscular, sad, angry, poorly drawn face, blurry, disfigured', aspectRatio: '16:9', },
          { key: 'void_knight', label: '角色表 | 虚空骑士', promptTemplate: 'Character sheet of a {personality} Void Knight, {style}, featuring {defining_features}. The weapon is {weapon}. Game setting is {game_setting}. Color palette is {color_palette}. Visual style similar to {references}. Front, side, and back view on a neutral background.', fields: { personality: { label: '性格特征', type: 'text', defaultValue: 'silent and disciplined' }, style: { label: '风格', type: 'text', defaultValue: 'sci-fi fantasy 3d render style' }, defining_features: { label: '定义特征', type: 'text', defaultValue: 'a full-body biomechanical armor with non-euclidean shapes and glowing cyan energy lines. The helmet is a featureless single glowing eye' }, weapon: { label: '武器/工具', type: 'text', defaultValue: 'a shapeshifting void energy spear' }, game_setting: { label: '游戏背景', type: 'text', defaultValue: 'a universe threatened by dimensional horrors' }, color_palette: { label: '调色板', type: 'text', defaultValue: 'deep purple and black with cyan highlights' }, references: { label: '参考作品', type: 'text', defaultValue: 'Warframe and Destiny' }, }, negativePrompt: 'human face, skin, cloth, leather, fantasy, medieval, cute, cartoon, blurry, poorly drawn', aspectRatio: '16:9', },
          // 11个概念图
          { key: 'abyssal_paladin', label: '概念图 | 深海圣骑士', promptTemplate: '{style} character concept art of {character_description}, wearing {equipment}, in a stance of {pose}, {lighting}, {details}', fields: { style: { label: '风格', type: 'text', defaultValue: 'Photorealistic, dark fantasy' }, character_description: { label: '角色描述', type: 'text', defaultValue: 'an abyssal paladin' }, equipment: { label: '服装/装备', type: 'text', defaultValue: 'ancient, barnacle-encrusted plate armor with bioluminescent coral growing on it' }, pose: { label: '姿态', type: 'text', defaultValue: 'standing guard in a sunken cathedral while wielding a trident that glows with faint blue light' }, lighting: { label: '灯光与情绪', type: 'text', defaultValue: 'dramatic underwater god rays' }, details: { label: '细节', type: 'text', defaultValue: 'highly detailed, cinematic, 8k' }, }, negativePrompt: 'painting, drawing, illustration, cartoon, anime, 3d render, deformed, disfigured, poorly drawn hands, blurry, low-resolution', aspectRatio: '16:9', },
          { key: 'magma_berserker', label: '概念图 | 熔岩狂战士', promptTemplate: '{style} character concept art of {character_description}, wearing {equipment}, in {pose}, lit by {lighting}, {details}', fields: { style: { label: '风格', type: 'text', defaultValue: 'Digital, epic fantasy' }, character_description: { label: '角色描述', type: 'text', defaultValue: 'a female magma berserker with skin cracked like cooling lava and a fiery glow from within' }, equipment: { label: '服装/装备', type: 'text', defaultValue: 'armor forged from obsidian and dragon bones' }, pose: { label: '姿态', type: 'text', defaultValue: 'a roaring battle stance with a massive two-handed axe' }, lighting: { label: '灯光与情绪', type: 'text', defaultValue: 'the intense heat and glow of a volcano' }, details: { label: '细节', type: 'text', defaultValue: 'trending on ArtStation' }, }, negativePrompt: 'photo, photorealistic, 3d render, deformed, disfigured, malformed, poorly drawn hands, blurry, grainy, cute, peaceful', aspectRatio: '16:9', },
          { key: 'celestial_scribe', label: '概念图 | 天空殿书记官', promptTemplate: '{style} character concept art of {character_description}, wearing {equipment}, in a pose of {pose}, {lighting}, {details}, clean line art', fields: { style: { label: '风格', type: 'text', defaultValue: 'Cel-shaded, anime key visual style' }, character_description: { label: '角色描述', type: 'text', defaultValue: 'a celestial scribe, an androgynous figure with wings made of pure starlight' }, equipment: { label: '服装/装备', type: 'text', defaultValue: 'flowing white and gold silk robes' }, pose: { label: '姿态', type: 'text', defaultValue: 'magically writing in a floating ethereal tome' }, lighting: { label: '灯光与情绪', type: 'text', defaultValue: 'soft and divine lighting' }, details: { label: '细节', type: 'text', defaultValue: 'ethereal, graceful' }, }, negativePrompt: 'photorealistic, realistic, photo, 3d render, detailed textures, messy lines, dark, gritty, deformed hands', aspectRatio: '16:9', },
          { key: 'plague_alchemist', label: '概念图 | 瘟疫炼金术士', promptTemplate: '{style} character concept art of {character_description}, wearing {equipment}, holding {pose}, {lighting}, {details}', fields: { style: { label: '风格', type: 'text', defaultValue: 'Gritty, horror fantasy' }, character_description: { label: '角色描述', type: 'text', defaultValue: 'a plague doctor alchemist' }, equipment: { label: '服装/装备', type: 'text', defaultValue: 'a dark leather coat and a crow-like mask with glowing green lenses' }, pose: { label: '姿态', type: 'text', defaultValue: 'a bubbling potion and a bone saw' }, lighting: { label: '灯光与情绪', type: 'text', defaultValue: 'eerie green alchemical lighting' }, details: { label: '细节', type: 'text', defaultValue: 'detailed textures, unsettling' }, }, negativePrompt: 'cartoon, anime, cute, clean, bright, cheerful, friendly, poorly drawn face, deformed, blurry', aspectRatio: '16:9', },
          { key: 'fungal_druid', label: '概念图 | 真菌德鲁伊', promptTemplate: '{style} character concept art of {character_description}, wearing {equipment}, calmly holding {pose}, {lighting}, {details}', fields: { style: { label: '风格', type: 'text', defaultValue: 'Mystical, fantasy' }, character_description: { label: '角色描述', type: 'text', defaultValue: 'a young female fungal druid with glowing mushrooms in her hair' }, equipment: { label: '服装/装备', type: 'text', defaultValue: 'clothes intertwined with moss' }, pose: { label: '姿态', type: 'text', defaultValue: 'a staff made of a giant, bioluminescent mushroom' }, lighting: { label: '灯光与情绪', type: 'text', defaultValue: 'ethereal glow in a misty forest' }, details: { label: '细节', type: 'text', defaultValue: 'detailed, atmospheric' }, }, negativePrompt: 'photorealistic, realistic, photo, bright, sunny, dry, urban, mechanical, deformed, disfigured', aspectRatio: '16:9', },
          { key: 'undead_samurai', label: '概念图 | 亡灵武士', promptTemplate: '{style} character concept art of {character_description}, wearing {equipment}, drawing {pose}, {lighting}, {details}', fields: { style: { label: '风格', type: 'text', defaultValue: 'Dark fantasy, Ghost of Tsushima style' }, character_description: { label: '角色描述', type: 'text', defaultValue: 'an undead samurai warrior, an armored skeleton wreathed in faint blue soulfire' }, equipment: { label: '服装/装备', type: 'text', defaultValue: 'tattered samurai armor' }, pose: { label: '姿态', type: 'text', defaultValue: 'a cursed katana in a spooky bamboo forest' }, lighting: { label: '灯光与情绪', type: 'text', defaultValue: 'eerie moonlight' }, details: { label: '细节', type: 'text', defaultValue: 'atmospheric, cinematic' }, }, negativePrompt: 'alive, human, flesh, cute, cheerful, bright, daylight, poorly drawn hands, disfigured', aspectRatio: '16:9', },
          { key: 'steampunk_captain', label: '概念图 | 空贼船长', promptTemplate: '{style} character concept art of {character_description}, wearing {equipment}, confidently {pose}, {lighting}, {details}', fields: { style: { label: '风格', type: 'text', defaultValue: 'Digital painting, steampunk' }, character_description: { label: '角色描述', type: 'text', defaultValue: 'a charismatic steampunk sky-pirate captain with a brass prosthetic eye' }, equipment: { label: '服装/装备', type: 'text', defaultValue: 'a leather duster over a waistcoat' }, pose: { label: '姿态', type: 'text', defaultValue: 'at the helm of his airship' }, lighting: { label: '灯光与情绪', type: 'text', defaultValue: 'golden hour lighting over a sea of clouds' }, details: { label: '细节', type: 'text', defaultValue: 'adventurous, detailed' }, }, negativePrompt: 'photorealistic, modern, futuristic, minimalist, simple, poorly drawn face, deformed, blurry', aspectRatio: '16:9', },
          { key: 'aether_gunslinger', label: '概念图 | 以太枪手', promptTemplate: '{style} character concept art of {character_description}, wearing {equipment}, aiming {pose}, {lighting}, {details}', fields: { style: { label: '风格', type: 'text', defaultValue: 'Fantasy-western, cinematic' }, character_description: { label: '角色描述', type: 'text', defaultValue: 'a stoic female aether-gunslinger with glowing arcane tattoos' }, equipment: { label: '服装/装备', type: 'text', defaultValue: 'a duster' }, pose: { label: '姿态', type: 'text', defaultValue: 'a pair of ornate revolvers that crackle with magical energy' }, lighting: { label: '灯光与情绪', type: 'text', defaultValue: 'dramatic lens flare at sunset' }, details: { label: '细节', type: 'text', defaultValue: 'dynamic' }, }, negativePrompt: 'modern, sci-fi, futuristic, poorly drawn hands, extra fingers, deformed, blurry, low-resolution', aspectRatio: '16:9', },
          { key: 'cosmic_cultist', label: '概念图 | 宇宙邪教徒', promptTemplate: '{style} character concept art of {character_description}, wearing {equipment}, raising {pose}, {lighting}, {details}', fields: { style: { label: '风格', type: 'text', defaultValue: 'Lovecraftian horror' }, character_description: { label: '角色描述', type: 'text', defaultValue: 'a cosmic cultist, face obscured by shadows' }, equipment: { label: '服装/装备', type: 'text', defaultValue: 'dark, tattered robes' }, pose: { label: '姿态', type: 'text', defaultValue: 'a strange, non-euclidean relic' }, lighting: { label: '灯光与情绪', type: 'text', defaultValue: 'unsettling, purple and green cosmic light' }, details: { label: '细节', type: 'text', defaultValue: 'atmospheric' }, }, negativePrompt: 'bright, cheerful, friendly, normal, human, safe, daylight, poorly drawn face, deformed', aspectRatio: '16:9', },
          { key: 'living_ink_tattooist', label: '概念图 | 活体墨水纹身师', promptTemplate: '{style} character concept art of {character_description}, using {pose}, {lighting}, {details}', fields: { style: { label: '风格', type: 'text', defaultValue: 'Urban fantasy' }, character_description: { label: '角色描述', type: 'text', defaultValue: 'a mystical tattooist whose own body is covered in animated tattoos' }, pose: { label: '姿态', type: 'text', defaultValue: 'a needle made of light to ink a glowing, magical pattern' }, lighting: { label: '灯光与情绪', type: 'text', defaultValue: 'warm, intimate, lantern-lit studio' }, details: { label: '细节', type: 'text', defaultValue: 'magical, detailed' }, }, negativePrompt: 'photorealistic, 3d render, bright daylight, fighting, chaotic, deformed hands, blurry, disfigured', aspectRatio: '16:9', },
          { key: 'dream_weaver', label: '概念图 | 梦境编织者', promptTemplate: '{style} character concept art of {character_description}, sitting on {pose}, {lighting}, {details}', fields: { style: { label: '风格', type: 'text', defaultValue: 'Surreal, Lisa Frank meets fantasy' }, character_description: { label: '角色描述', type: 'text', defaultValue: 'a Dream Weaver, a child-like entity made of stardust' }, pose: { label: '姿态', type: 'text', defaultValue: 'a crescent moon and weaving strands of light into tangible dreams' }, lighting: { label: '灯光与情绪', type: 'text', defaultValue: 'magical, swirling vortex of colorful dream-matter' }, details: { label: '细节', type: 'text', defaultValue: 'vibrant, whimsical' }, }, negativePrompt: 'realistic, photorealistic, dark, gritty, horror, scary, deformed, ugly, blurry', aspectRatio: '16:9', },
        ],
        options: { style: [], lighting: [], composition: [] },
      },
      worldbuilding: {
        label: '游戏环境与关键艺术图',
        subTemplates: [
          { key: 'crystal_city', label: '水晶浮空城', promptTemplate: 'High-fantasy, digital painting worldbuilding scene of a majestic floating city made of luminous crystals and white marble, featuring waterfalls cascading from the islands and elegant airships docking, bright, ethereal sunlight with lens flare creating a magical atmosphere, epic wide shot, panoramic view', fields: {}, negativePrompt: 'photorealistic, photo, dark, gritty, blurry, low-resolution', aspectRatio: '16:9', },
          { key: 'sunken_library', label: '沉没的亚特兰蒂斯图书馆', promptTemplate: 'Dark fantasy, cinematic worldbuilding scene of a vast, sunken library in Atlantis, featuring giant stone statues of ancient scholars covered in moss and coral, with schools of bioluminescent fish illuminating the aisles of preserved scrolls, mysterious, deep-sea ambient light with god rays piercing the water, interior shot', fields: {}, negativePrompt: 'dry, land, fire, bright, cheerful, poorly drawn', aspectRatio: '16:9', },
          { key: 'giants_forge', label: '巨人之 forge', promptTemplate: 'Epic fantasy, digital painting worldbuilding scene of a colossal forge built inside a hollowed-out mountain, featuring a river of lava flowing through the center and giant-sized anvils and hammers, intense, fiery glow from the lava and sparks from hammering creating a hot, powerful atmosphere, low angle shot looking up', fields: {}, negativePrompt: 'small, human-scale, cold, ice, clean, peaceful', aspectRatio: '16:9', },
          { key: 'pirate_harbor', label: '海盗共和国的垂直港湾', promptTemplate: 'Fantasy, cinematic worldbuilding scene of a multi-level, vertical pirate city built into the cliffs of a secret cove, featuring rickety rope bridges, cascading waterfalls, taverns carved into the rock, and captured ships repurposed as buildings, warm, chaotic atmosphere lit by torches, lanterns, and bioluminescent fungi, dynamic wide shot showing the verticality', fields: {}, negativePrompt: 'modern, sci-fi, clean, organized, peaceful, desert, blurry', aspectRatio: '16:9', },
          { key: 'ascendants_peak', label: '飞升者之巅', promptTemplate: 'High-fantasy, cinematic worldbuilding scene of a serene temple monastery perched on a snowy, impossibly high mountain peak, featuring prayer flags fluttering in the wind and a lone, meditating monk, clear, cold morning light with the sun rising above a sea of clouds, minimalist, breathtaking wide shot', fields: {}, negativePrompt: 'dark, cluttered, chaotic, warm, blurry', aspectRatio: '16:9', },
          { key: 'whispering_fen', label: '低语沼泽', promptTemplate: 'Horror fantasy, atmospheric worldbuilding scene of a twisted, haunted swamp at twilight, featuring gnarled, moss-covered trees with hanging skeletons and eerie will-o\'-the-wisps floating over murky water, foggy, melancholic twilight with a sickly green glow, eye-level shot', fields: {}, negativePrompt: 'bright, sunny, cheerful, safe, clean', aspectRatio: '16:9', },
          { key: 'orbital_garden', label: '轨道花园空间站', promptTemplate: 'Utopian sci-fi, digital painting worldbuilding scene of a massive, ring-shaped space station\'s interior, converted into a lush, bio-diverse park, featuring a zero-gravity river and exotic alien plants growing under a simulated sun, bright, clean, optimistic lighting, wide interior shot', fields: {}, negativePrompt: 'dark, dystopian, rusty, post-apocalyptic, gritty', aspectRatio: '16:9', },
          { key: 'desert_dynasty', label: '被遗忘的沙漠王朝', promptTemplate: 'Photorealistic, fantasy worldbuilding scene of the colossal ruins of a forgotten city half-buried in sand dunes, featuring giant statues of pharaohs and crumbling pyramids, harsh, golden hour sunlight creating long, dramatic shadows, epic wide shot', fields: {}, negativePrompt: 'forest, jungle, water, snow, modern, blurry', aspectRatio: '16:9', },
          { key: 'mushroom_forest', label: '蘑菇森林之心', promptTemplate: 'Whimsical fantasy, digital painting worldbuilding scene of the heart of a forest where all trees are giant, bioluminescent mushrooms, featuring small, fairy-like creatures flying between the mushroom caps, magical, soft, multi-colored glow from the flora, low angle shot looking up', fields: {}, negativePrompt: 'realistic, photorealistic, normal trees, dark, scary', aspectRatio: '16:9', },
          { key: 'highway_graveyard', label: '后启示录高速公路墓地', promptTemplate: 'Gritty, post-apocalyptic worldbuilding scene of a massive, rusted highway interchange, now a graveyard for decaying cars and trucks, featuring survivors\' makeshift camps built among the wreckage, overcast, gloomy, desaturated lighting, high angle shot looking down', fields: {}, negativePrompt: 'pristine, clean, futuristic, lush, vibrant, working cars', aspectRatio: '16:9', },
          { key: 'steampunk_parliament', label: '蒸汽朋克议会厅', promptTemplate: 'Steampunk, digital painting worldbuilding scene of a grand, ornate parliament hall, featuring intricate brass and copper clockwork mechanisms powering the building and automatons serving the politicians, warm, dramatic interior lighting from gas lamps and large windows, wide shot', fields: {}, negativePrompt: 'modern, minimalist, sci-fi, simple, blurry', aspectRatio: '16:9', },
          { key: 'alien_jungle', label: '外星丛林', promptTemplate: 'Sci-fi, cinematic worldbuilding scene of a vibrant, alien jungle on a distant planet, featuring bizarre, pulsating flora and fauna, and two suns in the sky casting strange colored shadows, bright, saturated, otherworldly lighting, immersive first-person view', fields: {}, negativePrompt: 'earth-like, normal plants, dark, monochrome', aspectRatio: '16:9', },
          { key: 'vampire_ballroom', label: '吸血鬼伯爵的舞厅', promptTemplate: 'Gothic horror, cinematic worldbuilding scene of an opulent, yet decaying, baroque ballroom, featuring ghostly figures waltzing to silent music under a giant, dusty chandelier, moody, dramatic moonlight streaming through tall, arched windows, wide interior shot', fields: {}, negativePrompt: 'bright, modern, clean, cheerful, sunny', aspectRatio: '16:9', },
          { key: 'sky_pirate_cove', label: '天空海盗的秘密港湾', promptTemplate: 'Fantasy, adventurous worldbuilding scene of a hidden cove carved into a giant floating island, where various steampunk airships are docked for repair, featuring rope bridges connecting different levels and a bustling pirate tavern, warm, late afternoon sunlight, dynamic composition', fields: {}, negativePrompt: 'ground, sea, modern, peaceful, quiet', aspectRatio: '16:9', },
          { key: 'time_frozen_square', label: '时间静止的城市广场', promptTemplate: 'Surreal, cinematic worldbuilding scene of a bustling 1950s city square that is completely frozen in time, featuring people, cars, and even a flock of pigeons suspended mid-air, strange, ethereal, slightly desaturated lighting, eye-level shot', fields: {}, negativePrompt: 'moving, modern, fantasy, dark, blurry', aspectRatio: '16:9', },
          { key: 'dwarven_kingdom', label: '地底矮人王国', promptTemplate: 'High-fantasy, digital painting worldbuilding scene of a massive subterranean dwarven city, featuring architecture carved directly from the rock, glowing veins of mithril in the walls, and a grand throne room, warm, torchlight and forge-glow, epic wide shot showing the scale', fields: {}, negativePrompt: 'sky, sun, trees, elves, fragile, poorly drawn', aspectRatio: '16:9', },
          { key: 'mad_max_arena', label: '疯狂麦克斯式的竞技场', promptTemplate: 'Post-apocalyptic, gritty worldbuilding scene of a gladiatorial arena made from scrap metal and old ship containers, featuring heavily modified battle vehicles kicking up dust, harsh, dusty desert sunlight, action-packed wide shot', fields: {}, negativePrompt: 'clean, lush, futuristic, peaceful, forest', aspectRatio: '16:9', },
          { key: 'elven_courtyard', label: '精灵女王的庭院', promptTemplate: 'High-fantasy, ethereal worldbuilding scene of a beautiful, serene courtyard in an elven palace, featuring ancient, silver-barked trees, a magical fountain, and elegant elven architecture, soft, magical, dappled lighting, peaceful, symmetrical composition', fields: {}, negativePrompt: 'dark, gritty, dwarven, orcish, chaotic', aspectRatio: '16:9', },
          { key: 'cosmic_horror_bones', label: '宇宙恐怖巨兽的骸骨', promptTemplate: 'Sci-fi horror, cinematic worldbuilding scene of a desolate alien moon, featuring the colossal, fossilized skeleton of a Lovecraftian space creature, with astronauts exploring near its giant ribcage for scale, eerie, low-gravity lighting from a distant nebula, ultra-wide shot', fields: {}, negativePrompt: 'earth, life, plants, water, bright, safe', aspectRatio: '16:9', },
        ],
        options: { style: [], lighting: [], composition: [] },
      },
      ui_design: {
        label: '游戏UI与地图设计',
        subTemplates: [
          { key: 'celestial_skill_tree', label: '星象技能树', promptTemplate: 'An elegant, fantasy RPG UI for a skill tree screen, featuring a celestial map of the night sky where each star is a skill and constellations represent skill paths. The background is a swirling nebula. The lighting is a cool, magical glow emanating from the stars. Unlocking a skill makes the star shine brighter, giving players clear feedback.', fields: {}, negativePrompt: 'sci-fi, hexagonal, geometric, modern, paper, blurry', aspectRatio: '1:1', },
          { key: 'dwarven_rune_crafting', label: '矮人符文制作界面', promptTemplate: 'A richly detailed RPG crafting screen for rune-crafting, featuring an ornate border of carved stone and inlaid gold. The interface displays sockets on a weapon and a grid of available runes. Each rune is illustrated with a glowing, intricate design. The lighting is warm and inviting, as if lit by a forge. Interaction zones are marked by a solid, glowing highlight.', fields: {}, negativePrompt: 'sci-fi, modern, minimalist, sleek, cold, blurry icons', aspectRatio: '1:1', },
          { key: 'alchemist_recipe_book', label: '炼金术士的药剂配方书', promptTemplate: 'A detailed RPG UI for a potion recipe book, designed to look like an old leather-bound tome. It features hand-drawn illustrations of ingredients like "Mandrake Root". Categories for "Healing" and "Poisons" are defined by elegant, calligraphic tabs. The lighting is warm, as if reading by candlelight. Pages turn with a realistic animation.', fields: {}, negativePrompt: 'futuristic, screen, digital, minimalist, blurry text', aspectRatio: '1:1', },
          { key: 'starship_nav_map', label: '星际飞船导航地图', promptTemplate: 'A detailed sci-fi UI for a 3D star map, featuring glowing constellations, trade routes, and planetary systems. The player\'s ship is a distinct icon. The map can be rotated and zoomed. The lighting is a cool, holographic blue. Selected planets are highlighted with a circular data readout, giving players clear feedback.', fields: {}, negativePrompt: '2D, flat, fantasy, paper, simple, blurry', aspectRatio: '1:1', },
          { key: 'elven_char_creation', label: '精灵风格角色创建界面', promptTemplate: 'An elegant RPG character creation screen in a fantasy realm, featuring ornate borders of intertwining silver vines and moonstones. It displays options for hairstyles and facial tattoos. The character model is shown in the center. The lighting is soft and ethereal. Sliders for customization are clearly defined and glow softly when adjusted.', fields: {}, negativePrompt: 'gritty, dark, dwarven, sci-fi, cluttered', aspectRatio: '1:1', },
          { key: 'wasteland_survival_guide', label: '废土生存指南', promptTemplate: 'A gritty, post-apocalyptic UI for a survival guide, designed to look like a dirty, worn-out field manual. It features hand-scrawled notes, coffee stains, and taped-on polaroid photos of mutated creatures. Categories are marked with rough, stenciled text. The lighting is harsh and practical.', fields: {}, negativePrompt: 'clean, pristine, futuristic, fantasy, elegant', aspectRatio: '1:1', },
          { key: 'dialogue_noble', label: '对话框 - 贵族', promptTemplate: 'A clean, ornate RPG dialogue box for speaking with a noble character, featuring a polished wood texture with golden filigree borders. The character\'s portrait is displayed in a detailed, painted style. The text font is an elegant serif. Interaction options like "Persuade" are clearly marked.', fields: {}, negativePrompt: 'simple, modern, sci-fi, gritty, blurry text', aspectRatio: '1:1', },
          { key: 'dialogue_robot', label: '对话框 - 机器人', promptTemplate: 'A clean, minimalist sci-fi dialogue box for speaking with an AI, featuring a semi-transparent, holographic glass interface. The text font is a crisp, digital sans-serif. The AI\'s "portrait" is an abstract, pulsating waveform.', fields: {}, negativePrompt: 'fantasy, rustic, ornate, paper, warm', aspectRatio: '1:1', },
          { key: 'loading_screen_tomb', label: '加载界面 - 古墓', promptTemplate: 'A detailed RPG loading screen for an ancient tomb, featuring a central, beautifully rendered 3D model of a key artifact from the level. Game tips are displayed at the bottom in clear, runic-style text. A progress bar is designed as a snake eating its own tail. The lighting is dark and mysterious.', fields: {}, negativePrompt: 'bright, cheerful, simple, blurry', aspectRatio: '1:1', },
          { key: 'magic_card_ui', label: '魔法卡牌', promptTemplate: 'A richly detailed UI for a magical card, featuring an ornate, elemental frame (fire, ice, etc.). The card displays a beautiful illustration of a creature or spell, its attack/defense stats, and a description of its ability. The lighting is magical, with glows emanating from the card\'s gems.', fields: {}, negativePrompt: 'simple, minimalist, sci-fi, blurry art', aspectRatio: '1:1', },
          { key: 'world_map_parchment', label: '世界地图 - 羊皮纸', promptTemplate: 'A detailed RPG world map in a fantasy realm, designed to look like an old, hand-drawn parchment map with sea monsters in the oceans and illustrations of key cities. The lighting appears natural, as if on a table. The player\'s location is marked with a distinct, iconic pin.', fields: {}, negativePrompt: 'modern, satellite view, sci-fi, 3D', aspectRatio: '1:1', },
          { key: 'achievement_unlock', label: '成就解锁通知', promptTemplate: 'A celebratory UI notification for an "Achievement Unlocked", featuring a golden laurel wreath icon and a metallic banner. The text is bold and clear. The notification appears with a shimmering, sparkling particle effect, giving players clear, positive feedback.', fields: {}, negativePrompt: 'subtle, dark, sad, mundane', aspectRatio: '1:1', },
          { key: 'health_mana_orbs', label: '生命/法力条', promptTemplate: 'A detailed RPG HUD element, featuring ornate, spherical orbs for Health (red, pulsating liquid) and Mana (blue, swirling energy). The orbs are set in a decorative stone or metal frame. The lighting comes from within the orbs themselves.', fields: {}, negativePrompt: 'simple bars, minimalist, sci-fi, blurry', aspectRatio: '1:1', },
          { key: 'cooking_interface', label: '烹饪界面', promptTemplate: 'A cozy RPG crafting screen for cooking, designed to look like a rustic wooden cutting board. It features slots for ingredients and a central "mixing bowl" area. Available recipes are shown in a recipe book on the side. The lighting is warm and inviting.', fields: {}, negativePrompt: 'industrial, sci-fi, sterile, dark', aspectRatio: '1:1', },
          { key: 'minimap_hightech', label: '小地图 - 科技感', promptTemplate: 'A sleek, sci-fi UI for a circular minimap, featuring a semi-transparent holographic display. It shows enemy locations as red dots and objectives as glowing star icons. The border of the minimap pulses gently.', fields: {}, negativePrompt: 'square, fantasy, paper, cluttered', aspectRatio: '1:1', },
          { key: 'shop_ui_merchant', label: '商店界面 - 旅行商人', promptTemplate: 'A detailed RPG shop screen for a traveling merchant, featuring items displayed on a worn-out cloth spread on the ground. Categories are defined by hand-written wooden signs. The lighting is natural daylight. The player\'s gold count is clearly visible in a leather pouch icon.', fields: {}, negativePrompt: 'modern, clean, futuristic, indoor', aspectRatio: '1:1', },
          { key: 'talent_tree_nature', label: '天赋树 - 自然主题', promptTemplate: 'A beautiful RPG talent tree screen for a druid, designed as a giant, growing tree. Each branch is a different specialization, and each leaf is a talent. Unlocking a talent makes the leaf glow and a new branch grow. The lighting is soft, dappled sunlight.', fields: {}, negativePrompt: 'geometric, straight lines, sci-fi, dark', aspectRatio: '1:1', },
          { key: 'quest_log', label: '任务日志', promptTemplate: 'A detailed RPG UI for a quest log, designed like a adventurer\'s personal journal. It features tabs for "Active" and "Completed" quests. Each quest has a title and a summary written in a narrative, first-person style. The lighting is neutral and easy to read.', fields: {}, negativePrompt: 'modern, sterile, list view, blurry text', aspectRatio: '1:1', },
          { key: 'party_selection', label: '队伍选择界面', promptTemplate: 'A detailed RPG party selection screen, featuring beautifully illustrated, full-body portraits of available companions. Each portrait has the character\'s class icon and health bar below it. Selecting a character makes their portrait glow and step forward, giving clear feedback. The lighting is heroic and warm.', fields: {}, negativePrompt: 'simple icons, text only, dark, blurry portraits', aspectRatio: '1:1', },
        ],
        options: { style: [], lighting: [], composition: [] },
      },
    },
  },
  ecommerce: {
    label: '电子商务',
    useCases: {
      studio_shots: {
        label: '工作室产品图',
        subTemplates: [
          { key: 'luxury_watch', label: '奢华腕表', promptTemplate: 'Professional studio product photo of a luxury Swiss watch with a stainless steel band, macro shot showing intricate details, on a dark, polished marble surface, clean, professional studio lighting with soft shadows', fields: {}, negativePrompt: 'blurry, grainy, dust, scratches, distracting background, poor lighting', aspectRatio: '1:1', },
          { key: 'skincare_bottle', label: '护肤品瓶', promptTemplate: 'Minimalist studio product photo of a sleek, white skincare bottle with a gold cap, standing on a pedestal with a single drop of water running down its side, clean, bright, high-key lighting', fields: {}, negativePrompt: 'cluttered, dark, shadows, blurry, distracting elements', aspectRatio: '3:4', },
          { key: 'headphones', label: '高端耳机', promptTemplate: 'Sleek studio product photo of a pair of black, wireless over-ear headphones, hero shot, on a simple, light grey background, perfect, even studio lighting to highlight the matte and gloss textures', fields: {}, negativePrompt: 'messy, dusty, fingerprints, harsh shadows, blurry', aspectRatio: '1:1', },
          { key: 'chocolate_bar', label: '手工巧克力', promptTemplate: 'Appetizing studio product photo of a gourmet dark chocolate bar, partially unwrapped from its elegant paper packaging, with a few cocoa beans scattered nearby, on a slate surface, warm, soft lighting', fields: {}, negativePrompt: 'unappetizing, messy, melted, poor lighting, blurry', aspectRatio: '4:3', },
          { key: 'sneaker', label: '运动鞋', promptTemplate: 'Dynamic studio product photo of a single, clean, high-tech sneaker, angled to show its design and sole, on a pure white background, crisp, bright, energetic studio lighting', fields: {}, negativePrompt: 'dirty, worn, scuffed, dark, blurry, flat', aspectRatio: '1:1', },
          { key: 'perfume_bottle', label: '香水瓶', promptTemplate: 'Elegant studio product photo of a crystal perfume bottle, with light refracting through the glass and liquid, surrounded by a subtle mist, on a reflective black surface, dramatic, high-contrast lighting', fields: {}, negativePrompt: 'plain, boring, flat lighting, blurry, dust', aspectRatio: '3:4', },
          { key: 'smartphone', label: '智能手机', promptTemplate: 'Clean, tech-focused studio product photo of a new smartphone, showing its slim profile and vibrant screen, floating at a slight angle against a minimalist gradient background, perfect, edge-to-edge screen lighting', fields: {}, negativePrompt: 'fingerprints, smudges, scratches, glare, outdated model, blurry', aspectRatio: '1:1', },
          { key: 'wine_bottle', label: '红酒瓶', promptTemplate: 'Sophisticated studio product photo of an unlabeled red wine bottle with a pristine wax seal, next to an elegant wine glass, on a dark, rustic wooden surface, moody, low-key lighting with a single key light highlighting the bottle\'s shape', fields: {}, negativePrompt: 'cheap, label, bright, messy, dust, blurry', aspectRatio: '3:4', },
          { key: 'engagement_ring', label: '订婚戒指', promptTemplate: 'Macro studio product photo of a diamond engagement ring in its box, focusing on the sparkle and cut of the diamond, on a black velvet background, bright, sparkling, multi-point lighting to maximize brilliance', fields: {}, negativePrompt: 'dull, blurry, out of focus, yellow diamond, distracting elements', aspectRatio: '1:1', },
          { key: 'handbag', label: '手提包', promptTemplate: 'Luxury fashion studio product photo of a leather handbag, standing upright to show its structure and details like stitching and hardware, on a neutral, seamless paper background, soft, diffused, even lighting', fields: {}, negativePrompt: 'cheap, fake leather, worn, misshapen, harsh shadows, blurry', aspectRatio: '4:3', },
        ],
        options: { style: [], lighting: [], composition: [] },
      },
      lifestyle_shots: {
        label: '生活方式产品图',
        subTemplates: [
          { key: 'coffee_mug', label: '咖啡杯', promptTemplate: 'Cozy lifestyle photo of a steaming ceramic coffee mug being held by two hands on a rainy day, with a blurred background of a window with raindrops, warm, soft, indoor lighting', fields: {}, negativePrompt: 'empty, cold, studio, unrealistic, poorly drawn hands', aspectRatio: '1:1', },
          { key: 'laptop', label: '笔记本电脑', promptTemplate: 'Productive lifestyle photo of an open, slim laptop on a clean wooden desk, next to a notebook and a cup of coffee, with a blurred background of a modern home office, bright, natural morning light from a window', fields: {}, negativePrompt: 'cluttered, messy, old laptop, fingerprints, dark', aspectRatio: '16:9', },
          { key: 'running_shoes', label: '跑鞋 (动态)', promptTemplate: 'Dynamic lifestyle photo of a pair of vibrant running shoes on the feet of a runner in mid-stride on a city bridge at sunrise, motion blur on the background, warm sunrise light, low angle shot', fields: {}, negativePrompt: 'static, still, blurry subject, poor composition, unrealistic', aspectRatio: '16:9', },
          { key: 'backpack', label: '背包', promptTemplate: 'Adventurous lifestyle photo of a durable hiking backpack leaning against a rock, with a stunning mountain landscape in the background, bright, clear daylight', fields: {}, negativePrompt: 'studio, indoor, urban, clean, unused', aspectRatio: '4:3', },
          { key: 'sunglasses', label: '太阳镜', promptTemplate: 'Chic lifestyle photo of a pair of stylish sunglasses resting on a table at a beachside cafe, with a tropical drink and the ocean blurred in the background, bright, sunny, vacation-vibe lighting', fields: {}, negativePrompt: 'indoor, dark, dirty lenses, cheap, unrealistic', aspectRatio: '1:1', },
          { key: 'yoga_mat', label: '瑜伽垫', promptTemplate: 'Serene lifestyle photo of a rolled-up yoga mat on the floor of a bright, airy studio with large windows and plants, soft, peaceful morning light', fields: {}, negativePrompt: 'dirty, messy, dark, cluttered, unrealistic', aspectRatio: '3:4', },
          { key: 'chefs_knife', label: '厨师刀', promptTemplate: 'Action lifestyle photo of a professional chef\'s knife in mid-slice through a fresh tomato on a wooden cutting board, with other fresh vegetables around, bright, clean kitchen lighting', fields: {}, negativePrompt: 'dull, rusty, still, messy, dangerous, poorly drawn hands', aspectRatio: '4:3', },
          { key: 'sofa', label: '沙发', promptTemplate: 'Inviting lifestyle photo of a comfortable, stylish sofa in a beautifully decorated living room, with soft pillows and a throw blanket, warm, ambient evening light from lamps', fields: {}, negativePrompt: 'empty, sterile, uncomfortable, outdoor, messy', aspectRatio: '16:9', },
          { key: 'guitar_campfire', label: '篝火旁的吉他', promptTemplate: 'Atmospheric lifestyle photo of an acoustic guitar leaning against a log by a crackling campfire at night, with blurred figures in the background, warm, flickering firelight', fields: {}, negativePrompt: 'studio, daylight, broken, unrealistic', aspectRatio: '1:1', },
        ],
        options: { style: [], lighting: [], composition: [] },
      },
      ad_creative: {
        label: '广告创意',
        subTemplates: [
          { key: 'premium_perfume', label: '高级香水', promptTemplate: 'Minimalist ad creative for a unisex perfume bottle, featuring the bottle half-submerged in clean, still water with a single flower petal floating nearby, set against a soft, out-of-focus pastel background, with soft, natural, diffused lighting evoking a fresh and clean feeling, ample negative space', fields: {}, negativePrompt: 'cluttered, dark, harsh shadows, vibrant colors, messy', aspectRatio: '3:4', },
          { key: 'limited_sneakers', label: '限量版运动鞋', promptTemplate: 'Urban, high-fashion ad creative for a pair of limited-edition sneakers, featuring the shoes levitating in the center of a gritty, graffiti-covered alleyway, with dramatic, high-contrast neon and shadow lighting creating an edgy, exclusive mood, incorporating street-style brand elements', fields: {}, negativePrompt: 'clean, minimalist, studio, natural light, boring, static', aspectRatio: '1:1', },
          { key: 'leather_handbag', label: '真皮手提包', promptTemplate: 'Sophisticated ad creative for a designer leather handbag, featuring the bag placed on the passenger seat of a vintage luxury car, with a pair of silk gloves resting beside it, with soft, golden hour light streaming through the car window, evoking a feeling of timeless elegance and escape', fields: {}, negativePrompt: 'cheap, fake leather, modern car, studio, bright', aspectRatio: '4:3', },
          { key: 'outdoor_jacket', label: '户外夹克', promptTemplate: 'Adventurous ad creative for a waterproof outdoor jacket, featuring a person wearing the jacket standing on a misty mountain peak, looking out over a vast valley, with dramatic, moody, atmospheric lighting from an overcast sky, emphasizing durability and exploration', fields: {}, negativePrompt: 'sunny, clear sky, studio, clean, static pose', aspectRatio: '16:9', },
          { key: 'artisanal_coffee', label: '手工咖啡', promptTemplate: 'Cozy and warm ad creative for a bag of artisanal coffee beans, featuring a steaming mug of freshly brewed coffee on a rustic wooden table, next to an open book and the coffee bag, with soft morning light filtering through a nearby window, creating an inviting and relaxing mood', fields: {}, negativePrompt: 'instant coffee, messy, dark, cold, sterile', aspectRatio: '1:1', },
          { key: 'energy_bar', label: '健康能量棒', promptTemplate: 'Dynamic ad creative for a healthy energy bar, featuring the bar unwrapped with ingredients like nuts and berries exploding outwards in a beautiful, frozen-motion shot, set against a clean, vibrant, single-color background that matches the brand\'s packaging, with bright, energetic studio lighting', fields: {}, negativePrompt: 'still, messy, dark, unappetizing', aspectRatio: '16:9', },
          { key: 'craft_beer', label: '精酿啤酒', promptTemplate: 'Sociable and friendly ad creative for a craft beer, featuring a close-up of a condensation-covered beer glass filled with amber liquid, with the blurred background of a lively, warm-lit pub with friends laughing, creating a feeling of community and good times, shallow depth of field', fields: {}, negativePrompt: 'empty, bottle only, studio, sad, quiet', aspectRatio: '1:1', },
          { key: 'organic_juice', label: '有机果汁', promptTemplate: 'Fresh and vibrant ad creative for an organic juice, featuring the bottle surrounded by a splash of its own liquid and fresh, whole fruits (oranges, strawberries, mangoes), set against a clean, pure white background, with bright, natural, high-key lighting to emphasize freshness and health', fields: {}, negativePrompt: 'artificial, sugary, dark, moody', aspectRatio: '3:4', },
          { key: 'noise_cancelling_headphones', label: '降噪耳机', promptTemplate: 'Minimalist and serene ad creative for noise-cancelling headphones, featuring a person wearing the headphones with their eyes closed and a peaceful expression, while the chaotic, blurry background of a busy subway station fades into a calm, solid color around them, illustrating the product\'s key benefit', fields: {}, negativePrompt: 'loud, cluttered, messy, person looks stressed', aspectRatio: '1:1', },
          { key: 'smart_home_speaker', label: '智能家居音箱', promptTemplate: 'Modern and helpful ad creative for a smart home speaker, featuring the sleek speaker on a kitchen counter, with glowing light rings as if it\'s answering a question, while in the background, a family is happily cooking together, with warm, inviting kitchen lighting', fields: {}, negativePrompt: 'empty room, dark, unused, old kitchen', aspectRatio: '16:9', },
          { key: 'scented_candle', label: '香薰蜡烛', promptTemplate: 'Relaxing and atmospheric ad creative for a scented candle, featuring the candle with a gently flickering flame as the centerpiece of a cozy, dimly lit living room, with soft blankets and a book visible in the blurred background, creating a mood of peace and self-care', fields: {}, negativePrompt: 'unlit, bright daylight, sterile, messy', aspectRatio: '1:1', },
          { key: 'electric_car', label: '电动汽车', promptTemplate: 'Futuristic and sleek ad creative for an electric car, featuring the car driving silently on a winding coastal road at night, with its LED headlights cutting through the darkness and the starry sky above, evoking a feeling of clean technology and freedom, cinematic wide shot', fields: {}, negativePrompt: 'daytime, traffic, city, old car, pollution', aspectRatio: '16:9', },
          { key: 'moisturizing_cream', label: '保湿面霜', promptTemplate: 'Clean and scientific ad creative for a moisturizing face cream, featuring a dollop of the cream showing its rich texture, next to the open jar, with abstract, glowing water molecules floating in the background, with clean, clinical, bright lighting to emphasize hydration and science', fields: {}, negativePrompt: 'oily, greasy, dark, messy', aspectRatio: '1:1', },
          { key: 'fitness_app', label: '健身APP', promptTemplate: 'Energetic and motivational ad creative for a fitness app, featuring a dynamic shot of a diverse group of people working out outdoors in a beautiful park at sunrise, all looking determined and happy, with the app\'s interface subtly overlaid on a phone in the foreground', fields: {}, negativePrompt: 'gym, indoor, sad, tired, unrealistic bodies', aspectRatio: '16:9', },
          { key: 'travel_agency', label: '旅行社', promptTemplate: 'Inspirational ad creative for a travel agency, featuring a "before and after" concept with a dull, grey office cubicle on one side and a stunning, vibrant tropical beach on the other, as if looking through a window, creating a strong desire for escape and adventure', fields: {}, negativePrompt: 'bad weather, crowded beach, sad', aspectRatio: '4:3', },
          { key: 'mattress', label: '床垫', promptTemplate: 'Peaceful and dreamy ad creative for a mattress, featuring a person sleeping soundly on the mattress which is floating on a soft, fluffy cloud in a starry night sky, evoking a feeling of ultimate comfort and deep sleep', fields: {}, negativePrompt: 'realistic bedroom, awake, uncomfortable, bright daylight', aspectRatio: '16:9', },
          { key: 'jewelry_necklace', label: '珠宝项链', promptTemplate: 'Dramatic and luxurious ad creative for a diamond necklace, featuring a close-up of the necklace being worn on the elegant neck of a model, with her face out of focus, set against a dark, velvet background, with a single, dramatic spotlight making the diamonds sparkle intensely', fields: {}, negativePrompt: 'full body shot, casual clothing, bright, blurry jewelry', aspectRatio: '3:4', },
          { key: 'holiday_sale', label: '节日促销', promptTemplate: 'Festive and celebratory ad creative for a holiday sale, featuring a beautifully wrapped gift box exploding with glittering confetti, ribbons, and small icons of products, set against a rich, festive red background, with bright, sparkling lighting, ample negative space for text like "50% OFF"', fields: {}, negativePrompt: 'sad, dark, mundane, messy', aspectRatio: '1:1', },
        ],
        options: { style: [], lighting: [], composition: [] },
      },
    },
  },
  social_media: {
    label: '社交媒体',
    useCases: {
      engagement_post: {
        label: '通用互动帖子',
        subTemplates: [
          { key: 'mood_poll', label: '“本周心情”投票帖', promptTemplate: 'Vibrant flat lay illustration of four different coffee mugs, each with a different mood face (happy, tired, energetic, mischievous), set against a clean, pastel-colored background, in a playful and bright tone, top-down symmetrical composition, leave ample space at the top for the text "Which mug is your mood this Monday?"', fields: {}, negativePrompt: 'realistic, photo, dark, messy, blurry', aspectRatio: '1:1', },
          { key: 'behind_the_scenes', label: '“幕后故事”工作台', promptTemplate: 'Authentic, candid photo of a craftsman\'s messy-but-organized workbench, featuring tools, leather scraps, and a half-finished product, set against a rustic workshop background, in a warm, industrious tone, detailed close-up composition, leave space for text overlay', fields: {}, negativePrompt: 'clean, minimalist, sterile, polished, fake', aspectRatio: '1:1', },
          { key: 'this_or_that', label: '“你更喜欢哪个？”产品对比', promptTemplate: 'Clean, minimalist photo of two versions of a product (e.g., a blue sneaker and a red sneaker) placed side-by-side, set against a neutral grey studio background, in a clean, decisive tone, perfectly centered composition, designed for a "This or That?" poll', fields: {}, negativePrompt: 'cluttered, dark, distracting elements, blurry', aspectRatio: '1:1', },
          { key: 'tips_infographic', label: '“小贴士”信息图', promptTemplate: 'Bright, friendly illustration of a central icon (like a lightbulb or a plant), with three empty speech bubbles radiating outwards for text, set against a soft, single-color background, in an educational and helpful tone, infographic-style composition, leave space for text overlay', fields: {}, negativePrompt: 'photorealistic, dark, complex, messy', aspectRatio: '1:1', },
          { key: 'celebrate_wins', label: '“庆祝小成就”帖', promptTemplate: 'Joyful photo of a team of diverse people laughing and giving a high-five in a modern office, with confetti subtly falling around them, set against a blurred office background, in a celebratory and genuine tone, candid action shot, leave space for text overlay', fields: {}, negativePrompt: 'sad, posed, stiff, dark, messy', aspectRatio: '1:1', },
          { key: 'seasonal_greeting', label: '季节性问候', promptTemplate: 'Cozy, atmospheric illustration of a window looking out onto a beautiful autumn scene with falling leaves, with a steaming mug placed on the windowsill inside, in a warm and peaceful tone, inviting composition, leave space on the window pane for text like "Hello, October!"', fields: {}, negativePrompt: 'summer, winter, bright, harsh, messy', aspectRatio: '1:1', },
          { key: 'quote_background', label: '引言背景图', promptTemplate: 'Aesthetic, moody photo of a beautiful, misty mountain range at sunrise, with a soft, ethereal light, in a calm and inspirational tone, minimalist composition with the subject in the lower third, leaving the top two-thirds as clear sky for a quote overlay', fields: {}, negativePrompt: 'sunny, city, people, cluttered, blurry', aspectRatio: '1:1', },
          { key: 'teaser_post', label: '“猜猜是什么”神秘预告', promptTemplate: 'Mysterious close-up photo of a small, intriguing part of a new product, showing its unique texture or material, set against a dark, out-of-focus background, in a suspenseful and curious tone, macro shot composition, leave space for text overlay', fields: {}, negativePrompt: 'full product view, bright, clear, revealing', aspectRatio: '1:1', },
          { key: 'ugc_showcase', label: '用户生成内容(UGC)风格展示', promptTemplate: 'Authentic, user-generated style photo of a happy customer using a product in their real life (e.g., wearing a backpack on a hike), shot to look like a high-quality phone picture, in a genuine and relatable tone, natural composition, leave space for a testimonial overlay', fields: {}, negativePrompt: 'studio, polished, perfect, posed, unrealistic', aspectRatio: '1:1', },
          { key: 'brand_values', label: '品牌价值展示', promptTemplate: 'Symbolic, minimalist illustration of two hands carefully holding a small, glowing plant sprout, representing sustainability and care, set against a clean, earthy-toned background, in a hopeful and sincere tone, centered composition, leave space for text overlay', fields: {}, negativePrompt: 'technology, city, complex, dark', aspectRatio: '1:1', },
        ],
        options: { style: [], lighting: [], composition: [] },
      },
      story_reels: {
        label: '故事与Reels视觉',
        subTemplates: [
          { key: 'pov_unboxing', label: '第一人称(POV)开箱', promptTemplate: 'Cinematic POV photo of hands opening a beautifully packaged product box, with tissue paper and the product just peeking out, first-person perspective composition, creating an exciting and personal unboxing atmosphere', fields: {}, negativePrompt: 'third-person, messy, dark, blurry product', aspectRatio: '9:16', },
          { key: 'satisfying_moment', label: '满足感十足的瞬间', promptTemplate: 'Cinematic photo of a close-up, slow-motion shot of honey being drizzled onto a stack of pancakes, dynamic, mouth-watering composition, creating a satisfying and delicious atmosphere', fields: {}, negativePrompt: 'static, messy, dark, unappetizing', aspectRatio: '9:16', },
          { key: 'product_tutorial', label: '产品使用教程', promptTemplate: 'Cinematic photo of hands demonstrating the simple, one-twist opening mechanism of a skincare jar, close-up on the action composition, creating a clear and helpful tutorial atmosphere', fields: {}, negativePrompt: 'full body shot, confusing, dark, blurry', aspectRatio: '9:16', },
          { key: 'dynamic_product_showcase', label: '动态产品展示', promptTemplate: 'Cinematic photo of a dress flowing and twirling as a person spins in a sunlit field, dynamic motion blur on the background, creating a free and joyful atmosphere', fields: {}, negativePrompt: 'static, mannequin, indoor, dark, stiff', aspectRatio: '9:16', },
          { key: 'quick_tour', label: '快速空间导览', promptTemplate: 'Cinematic photo from the perspective of walking into a beautifully decorated, clean, and organized room (e.g., a hotel room or a new office), wide-angle, inviting composition, creating a welcoming and impressive atmosphere', fields: {}, negativePrompt: 'cluttered, messy, dark, old', aspectRatio: '9:16', },
          { key: 'grwm', label: '“和我一起准备” (GRWM)', promptTemplate: 'Cinematic photo of a flat lay of all the products needed for a morning routine (e.g., coffee, skincare, outfit), beautifully arranged on a clean, white bedspread, top-down, organized composition, creating a calm and aspirational atmosphere', fields: {}, negativePrompt: 'messy, dark, chaotic, used products', aspectRatio: '9:16', },
          { key: 'dramatic_transformation', label: '戏剧性转变', promptTemplate: 'Cinematic photo capturing the moment a dull, colorless object is splashed with vibrant color paint, mid-splash with droplets frozen in the air, high-contrast, energetic composition, creating a surprising and transformative atmosphere', fields: {}, negativePrompt: 'still, dry, monochrome, blurry', aspectRatio: '9:16', },
          { key: 'immersive_experience', label: '沉浸式体验', promptTemplate: 'Cinematic photo from the point of view of someone putting on a pair of headphones, with the world outside the headphones beginning to blur and fade away, immersive, focused composition, creating a peaceful and focused atmosphere', fields: {}, negativePrompt: 'person not wearing headphones, clear background', aspectRatio: '9:16', },
          { key: 'product_detail_macro', label: '产品细节特写', promptTemplate: 'Cinematic photo showing an extreme macro shot of the intricate stitching on a leather wallet, with the rest of the wallet blurred into the background, detailed, high-quality composition, creating a sophisticated and well-crafted atmosphere', fields: {}, negativePrompt: 'full product, blurry details, cheap material', aspectRatio: '9:16', },
          { key: 'looping_background', label: '循环视频背景', promptTemplate: 'Cinematic photo of soft, abstract, slowly moving bokeh lights in brand colors (e.g., blue and gold), out-of-focus, beautiful composition, creating a calm and professional background atmosphere for text overlays', fields: {}, negativePrompt: 'sharp, in-focus, specific objects, chaotic', aspectRatio: '9:16', },
        ],
        options: { style: [], lighting: [], composition: [] },
      },
      platform_ad_creative: {
        label: '平台广告创意',
        subTemplates: [
          { key: 'skincare_painpoint', label: '解决“皮肤干燥”痛点 (Instagram)', promptTemplate: 'High-performance photo for an Instagram ad, featuring a side-by-side visual concept: one half shows a dry, cracked desert floor, the other half shows a smooth, dewy, fresh leaf, symbolizing skin transformation, with clean, clinical lighting, ample negative space for text overlay', fields: {}, negativePrompt: 'human face, messy, dark, blurry', aspectRatio: '4:3', },
          { key: 'energy_benefit', label: '展示“精力充沛”的收益 (TikTok)', promptTemplate: 'High-energy photo for a TikTok ad, featuring a person captured mid-leap, joyfully jumping out of bed with the sun streaming in, with the visual concept of "unleash your morning energy", with bright, dynamic, slightly overexposed sunlight, ample negative space for text overlay', fields: {}, negativePrompt: 'tired, sad, sitting, dark, blurry', aspectRatio: '9:16', },
          { key: 'scarcity_exclusive', label: '营造“独家限量”的稀缺感 (Instagram)', promptTemplate: 'High-performance photo for an Instagram ad, featuring a single, beautifully crafted product (e.g., a watch) spotlit on a pedestal inside a museum-like vault, with the visual concept of "a rare artifact", with dramatic, high-contrast spotlighting, ample negative space for text overlay', fields: {}, negativePrompt: 'cluttered, bright, multiple products, blurry', aspectRatio: '1:1', },
          { key: 'natural_ingredients', label: '突出“天然成分” (Instagram)', promptTemplate: 'High-performance photo for an Instagram ad, featuring a clear bottle of shampoo with fresh rosemary and mint leaves suspended inside the liquid, with the visual concept of "nature bottled", with clean, bright, natural lighting, ample negative space for text overlay', fields: {}, negativePrompt: 'artificial colors, opaque bottle, dark, messy', aspectRatio: '4:3', },
          { key: 'urgency_offer', label: '创造“限时优惠”的紧迫感 (Facebook)', promptTemplate: 'High-performance photo for a Facebook ad, featuring a product dissolving into sand at one end like an hourglass, with the visual concept of "time is running out", with dramatic, focused lighting, ample negative space for text overlay', fields: {}, negativePrompt: 'static, whole product, bright, playful', aspectRatio: '1:1', },
          { key: 'social_proof', label: '利用“社会认同” (Facebook)', promptTemplate: 'High-performance photo for a Facebook ad, featuring a product displayed with a beautiful, gold, five-star rating floating above it and a ribbon that says "Bestseller", with the visual concept of "customer approved", with warm, celebratory lighting, ample negative space for text overlay', fields: {}, negativePrompt: 'no stars, dark, messy, blurry', aspectRatio: '4:3', },
          { key: 'ultimate_comfort', label: '展示“终极舒适” (Instagram)', promptTemplate: 'High-performance photo for an Instagram ad, featuring a pair of feet wearing incredibly soft, fluffy socks, resting on a cloud, with the visual concept of "walking on air", with soft, dreamy, ethereal lighting, ample negative space for text overlay', fields: {}, negativePrompt: 'realistic floor, dirty, uncomfortable, dark', aspectRatio: '1:1', },
          { key: 'durability_test', label: '强调“坚固耐用” (TikTok)', promptTemplate: 'High-impact photo for a TikTok ad, featuring a rugged phone case captured mid-air after being dropped onto concrete, completely unharmed with the screen glowing, with the visual concept of "The Ultimate Drop Test", with dramatic, frozen-motion lighting, ample negative space for text overlay', fields: {}, negativePrompt: 'static, on the ground, broken phone, blurry', aspectRatio: '9:16', },
          { key: 'ease_of_use', label: '突出“易于使用” (Instagram)', promptTemplate: 'High-performance photo for an Instagram ad, featuring a complex, tangled knot of wires on one side and a single, sleek wireless charger on the other, with the visual concept of "from chaos to calm", with clean, minimalist lighting, ample negative space for text overlay', fields: {}, negativePrompt: 'messy on both sides, dark', aspectRatio: '1:1', },
          { key: 'luxury_experience', label: '营造“奢华体验” (Facebook)', promptTemplate: 'High-performance photo for a Facebook ad, featuring a hotel-quality, perfectly folded white towel with a single, elegant orchid on top, placed at the edge of a luxurious bathtub, with the visual concept of "five-star treatment at home", with soft, warm, spa-like lighting, ample negative space for text overlay', fields: {}, negativePrompt: 'messy, used towel, bright, cheap', aspectRatio: '4:3', },
        ],
        options: { style: [], lighting: [], composition: [] },
      },
    },
  },
};
